# Generated by Django 5.1.1 on 2024-10-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
        ('project', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(blank=True, related_name='article_images', to='coreapp.document')),
                ('tags', models.ManyToManyField(blank=True, to='project.tag')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_thumbnail', to='coreapp.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
