# Generated by Django 5.1.1 on 2024-09-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
        ('project', '0002_project_images_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_thumbnail', to='coreapp.document'),
            preserve_default=False,
        ),
    ]
